version: "3.7"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8090:8080

  collect:
    depends_on:
      - db
    build: ./collect
    ports:
      - 3001:3001
    working_dir: /
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./collect/wait-for-it.sh:/usr/local/bin/wait-for-it.sh
    command:
      - wait-for-it.sh
      - postgres:5432
      - --
      - python
      - ./pro/main.py

volumes:
  db-data:
